### ISSUE TITLE
Vite support 

### ISSUE THREAD

**Issue by JLarky** [DataDog/build-plugins#63]
I see that you are supporting Webpack and esbuild, but could I use this with Vite projects? Like Remix

**Comment by yoannmoinet** [comment]
Sorry for the delay.
We're currently revamping the plugin to support more bundlers.
We'll keep this issue updated once Vite is supported.

**Comment by yoannmoinet** [comment]
Quick update on this, v2 has shipped, and we can now support way more bundlers easily.

We're still stuck on the telemetry module that needs to be re-implemented for each new bundler, as it reports on bundlers' internals.

I'm thinking of maybe adding some universal telemetry, across all bundlers, to give some headroom to later implement a finer reporter for each bundler. So we don't end up with bundlers lacking the telemetry module altogether.

So... back to Vite support. 
The idea would be to first implement this universal part of the telemetry module, and once this is done, we'll publish the plugin for all the supported bundlers.

Do that sound good to you @JLarky?
